spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:33061/database
    username: root
    hikari:
      auto-commit: false
      maximum-pool-size: 7
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
#app:
#  datasource:
#    password: root
#    url: jdbc:mysql://localhost:33061/database
#    username: root
